Feature/footer
Tim-Pet/design-exercise pull request #5
Opened 2021-04-25 12:27 UTC by pascalweber85

divided list 2 into 2 lists

2021-04-25 22:35 UTC, Tim-Pet requested changes
Ich habe nur auf clean code gerade geschaut und für BEM keine Change requests gemacht, weil ich mir nicht sicher bin, ob ihr überhaupt bem benutzen wolltet. 
Sobald a und ul abgeändert wurden, kann es gemerged werden 🥳 Good Job

2021-04-25 22:35 UTC, Tim-Pet commented on src/styles/app-footer/app-footer.css
> +a {
Gebt dem am Besten eine eigene klasse. Wenn das so abgespeichert ist, macht ihr globale stylings für alle links, egal ob im footer oder nicht. also einfach eine klasse bspw. footer__link geben. (Gleicher gilt für ul in Zeile 11)

2021-04-25 22:35 UTC, Tim-Pet commented on src/styles/app-footer/app-footer.css
> +footer {
Genereller Hinweis, ihr habt kein BEM benutzt (Was vom Ding her überhaupt nicht schlimm ist!) Also just saying, wenn ihr nochmal durchgehen wollt, wie das mit Bem aussehen würde, sagt Bescheid.

2021-04-25 22:35 UTC, Tim-Pet commented on src/styles/app-footer/app-footer.css
> +@media (min-width: 1000px) {
Ihr styled pro list (list1, list2 usw) grid-template-column: 1. Dadurch wiederholt ihr das Attribut für eigentlich gleiche Elemente relativ oft. Best practise wäre es eine Klasse app-footer__list zu machen und da alle überschneidenden Stylings reinzupacken und dann für bspw. app-footer__list--one die individuellen stylings, wie bspw. margin-left zu setzen

2021-04-26 07:52 UTC, pascalweber85 commented on src/styles/app-footer/app-footer.css
> +a {
ok -  hab ich geändert

2021-04-26 07:53 UTC, pascalweber85 commented on src/styles/app-footer/app-footer.css
> +footer {
jo würde das gerne nochmal durchgehen

2021-04-26 08:00 UTC, pascalweber85 reviewed
done

2021-04-26 08:01 UTC, merged